# Generated by Django 4.2.5 on 2023-09-10 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Miembro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Poyecto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombredeproyecto', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Tarea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombredetarea', models.CharField(max_length=40)),
                ('estado', models.CharField(choices=[('TO DO', 'To Do'), ('WIP', 'Work in Progress'), ('DONE', 'Done')], max_length=20)),
            ],
        ),
    ]
