# Generated by Django 4.2.5 on 2023-09-10 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyecto1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='poyecto',
            name='descripcion',
            field=models.TextField(default='Ingrese una descripcion'),
        ),
    ]
