# Generated by Django 4.2.5 on 2023-09-11 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyecto1', '0002_poyecto_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poyecto',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
