# Generated by Django 4.2.5 on 2023-09-11 01:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyecto1', '0003_alter_poyecto_descripcion'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Poyecto',
            new_name='Proyecto',
        ),
    ]
