# Generated by Django 4.2.5 on 2023-09-22 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyecto1', '0004_rename_poyecto_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='miembro',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppProyecto1.miembro'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='miembro',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppProyecto1.miembro'),
        ),
        migrations.AddField(
            model_name='tarea',
            name='proyecto',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='AppProyecto1.proyecto'),
        ),
        migrations.AlterField(
            model_name='miembro',
            name='nombre',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
