# Generated by Django 4.2.5 on 2023-10-08 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyecto1', '0006_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='fechaDeCreacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='proyecto_imagenes/'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
