# Generated by Django 4.2.5 on 2023-10-10 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppProyecto1', '0008_alter_miembro_options_alter_proyecto_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='miembro',
            options={},
        ),
        migrations.AlterModelOptions(
            name='proyecto',
            options={},
        ),
    ]
